{{- if .Values.pullSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pullSecret.name | default (print .Chart.Name "-pull") }}
  labels:
    {{- include "rucoder.labels" (dict "Chart" .Chart "Release" .Release "name" "pull-secret") | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.pullSecret.dockerconfigjson | b64enc }}
{{- end }}
