{{- if .Values.persistence.repos.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-repos
  labels:
    {{- include "rucoder.labels" (dict "Chart" .Chart "Release" .Release "name" "repos") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.repos.size }}
  resources:
    requests:
      storage: {{ .Values.persistence.repos.size }}
  {{- end }}
{{- end }}
